ai/urls.py
from django.urls import path
from . import views


app_name = 'ai'

urlpatterns = [
        path('', views.IndexView.as_view(), name='index'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ai/', include('ai.urls')),
]

ai/models.py
from django.db import models

# Create your models here.

ai/forms.py
from django import forms # type: ignore

from imagekit.forms import ProcessedImageField # type: ignore
from imagekit.processors import ResizeToFill # type: ignore


class ImageUploadForm(forms.Form):
    file = forms.ImageField(label='画像ファイル')

    """ Djangoの画像を加工してくれる機能
    file = ProcessedImageField(spec_id='画像ファイル',
                            processors=[ResizeToFill(50, 50)],
                            format='JPEG',
                            options={'quality':60})
    """

ai/views.py
import numpy as np  # type: ignore
from django.shortcuts import render  # type: ignore
from django.views import generic  # type: ignore
from PIL import Image

from .cat_cnn import abs_path_file, predict
from .forms import ImageUploadForm


class IndexView(generic.FormView):
    """
    画像認識フォーム画面

    """

    template_name = "ai/index.html"
    form_class = ImageUploadForm

    def form_valid(self, form):
        # アップロードファイル本体を取得
        file = form.cleaned_data["file"]

        # ファイルを、50*50にリサイズし, ３色にする。
        img = Image.open(file).resize((50, 50)).convert("RGB")

        # 学習時と同じ形に画像データを変換する
        img_array = np.asarray(img)
        img_cmp = []
        img_cmp.append(img_array)
        img_cmp_array = np.array(img_cmp)

        file_path = abs_path_file()

        # 推論した結果を、テンプレートへ渡して表示
        context = {
            "result": predict(img_cmp_array, file_path),
        }
        return render(self.request, "ai/index.html", context)


"""
image_size = 50
X = []

def index(request):
    if request.method == "POST":
        form = ImageUploadForm(request.POST)
        if form.is_valid():
            file = form.cleaned_data['file']
            img = Image.open(file).resize((image_size, image_size)).convert('RGB')
            img_array = np.asarray(img)
            X = []
            X.append(img_array)
            X = np.array(X)
            return render(request, 'ai/index.html', {'result': predict(X)})
        else:
            form = ImageUploadForm

    return render(request, 'ai/index.html', {'form': form})
"""

ai/templates/ai/index.html
{% extends 'base.html' %}
{% load static %}

{% block ai-style %}
<link rel="stylesheet" href="{% static 'ai/css/ai-style.css' %}">
{% endblock %}

{% block content %}

<!-- ブロックを挿入する -->
<div class="container">
  <div class="row">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-8 col-sm-12 main-bar">
      <!-- 大型ディスプレイ -->
      <div class="jumbotron jumbotron-fluid">
	<div class="container">
	  <div style="display: flex;">
	    <img class="d-flex align-self-center mr-3" src="{% static 'home/image/home_cat.png' %}" alt="Generic placeholder image">
	    <h2>{% block title %}ネコ科分類器<{% endblock %}/h2>
	  </div>
	  <p>
	  この分類器は、猫・ライオン・チーターのいずれかを予測します。それ以外の画像を渡しても、このいずれかを予測するので慌てないでください。
	  </p>
	</div>
      </div>
      <!-- 大型ディスプレイ END -->

      <!-- コンテナ内　結果に応じて猫・ライオン・チーターの表示 -->
      <div class="container">
	<h1>{{ result }}</h1>
	<br>

	<!-- BootStrapのグリッドシステム -->
	<div class='row'>

	  <!-- 結果の詳細を表示 -->
	  <div class="col-lg-7 col-sm-12">
	    {% if result == '猫' %}
	    <ul>
	      <h3>特徴</h3>
	      <li>気分屋さん</li>
	      <li>隠れる場所が好き</li>
	      <li>水分補給がとても大事</li>
	      <li>半日近く寝る</li>
	      <li>好奇心が強い</li>
	    </ul>
	    {% elif result == 'ライオン' %}
	    <ul>
	      <h3>特徴</h3>
	      <li>百獣の王と言われているが一番強いわけではない</li>
	      <li>オスはたてがみがある</li>
	      <li>狩りはメスの仕事</li>
	      <li>自分より大きな動物は基本狙わない</li>
	    </ul>
	    {% elif result == 'チーター' %}
	    <ul>
	      <h3>特徴</h3>
	      <li>小さな顔</li>
	      <li>斑点柄</li>
	      <li>基本単独で行動</li>
	      <li>最高時速１００キロ</li>
	    </ul>
	    {% endif %}
	  </div>
	  <!-- 結果の詳細を表示 END -->

	  <!-- サイドバー　画像表示 -->
	  <div class="col-lg-5 col-sm-12">
	    {% if result == '猫' %}
	    <img src="{% static 'ai/cat_1.jpg' %}" width=100%>
	    {% elif result == 'ライオン' %}
	    <img src="{% static 'ai/lion.jpg' %}" width=100%>
	    {% elif result == 'チーター' %}
	    <img src="{% static 'ai/cheetah.jpg' %}" width=100%>
	    {% endif %}
	  </div>
	  <!-- サイドバー　画像表示 END -->

	</div>
	<br>
	<!-- BootStrapのグリッドシステム END -->

	<div>
	  <p><strong>※ 猫・ライオン・チーターの画像ファイル以外を渡した場合、類似だと思われるものを予測します</strong></p>
	</div>

	<!-- 画像認識の結果に対して「戻る」を表示 -->
	{% if result == '猫' %}
	<a href="{% url 'ai:index' %}">
	  <button type="submit" class="btn btn-outline-danger btn-lg btn-sm">戻る</button>
	</a>
	{% elif result == 'ライオン' %}
	<a href="{% url 'ai:index' %}">
	  <button type="submit" class="btn btn-outline-danger btn-lg btn-sm">戻る</button>
	</a>
	{% elif result == 'チーター' %}
	<a href="{% url 'ai:index' %}">
	  <button type="submit" class="btn btn-outline-danger btn-lg btn-sm">戻る</button>
	</a>
	{% else %}
	<form accept="image/*" method="POST" enctype='multipart/form-data'>
	  {% csrf_token %}
	  {{ form.file }}
	  <hr>
	  <input type="submit" class="btn btn-outline-success btn-lg btn-sm" value="予測">
	</form>
	{% endif %}
      </div>
    </div>
    <div class="col-lg-2">
    </div>
  </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<html lang="ja" prefix="og: http://ogp.me/ns#">
  <head>

    <!-- BootStrap CSS Link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- StaticFiles CSS -->
    {% block ai-style %}{% endblock %}

  </head>
  <body>

    <!-- Djangoテンプレートタグ -->

    {% block content %}
    {% endblock %}

    <!-- BootStrap jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>